### ISSUE TITLE
Creating a Domain

### ISSUE THREAD

**Issue by ClaytonNolen** [ClaytonNolen/GymProgram#55]

**Comment by ClaytonNolen** [comment]
Signed up to Netlify for a new domain and connected it to my github account.

**Comment by ClaytonNolen** [comment]
Apr 15, 09:53:49 AM: 305dbbec ERROR  FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:493:40)
    at _assert (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:497:15)
    at Component.instanceFactory (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6887:9)
    at Provider.getOrInitializeService (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:3287:27)
    at getAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6948:18)
    at file:///var/task/.netlify/server/chunks/firebase.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) {
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}Apr 15, 09:53:49 AM: 305dbbec ERROR  FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:493:40)
    at _assert (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:497:15)
    at Component.instanceFactory (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6887:9)
    at Provider.getOrInitializeService (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:3287:27)
    at getAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6948:18)
    at file:///var/task/.netlify/server/chunks/firebase.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) {
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}
Apr 15, 09:53:49 AM: 305dbbec Duration: 3.11 ms	Memory Usage: 105 MB	Apr 15, 09:53:49 AM: 6b0cbcdb ERROR  SvelteKitError: Not found: /favicon.ico
    at resolve2 (file:///var/task/.netlify/server/index.js:2853:18)
    at resolve (file:///var/task/.netlify/server/index.js:2685:34)
    at #options.hooks.handle (file:///var/task/.netlify/server/index.js:2928:71)
    at respond (file:///var/task/.netlify/server/index.js:2683:43) {
  status: 404,
  text: 'Not Found'
}Apr 15, 09:53:49 AM: 6b0cbcdb ERROR  FirebaseError: Firebase: Error (auth/invalid-api-key).
    at createErrorInternal (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:493:40)
    at _assert (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:497:15)
    at Component.instanceFactory (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6887:9)
    at Provider.getOrInitializeService (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:290:39)
    at Provider.initialize (file:///var/task/node_modules/@firebase/component/dist/esm/index.esm2017.js:234:31)
    at initializeAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:3287:27)
    at getAuth (file:///var/task/node_modules/@firebase/auth/dist/node-esm/totp-343dfe50.js:6948:18)
    at file:///var/task/.netlify/server/chunks/firebase.js:24:1
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:336:24) {
  code: 'auth/invalid-api-key',
  customData: { appName: '[DEFAULT]' }
}
Apr 15, 09:53:49 AM: 6b0cbcdb Duration: 3.05 ms	Memory Usage: 105 MB
